#! /bin/sh



pgrep -x sxhkd > /dev/null || sxhkd &



bspc monitor HDMI-2 -d 1 2 
bspc monitor DVI-D-1 -d 3 4
#bspc monitor Virtual1 -d 1 2 3


bspc config border_width         3
bspc config window_gap           5 
bspc config top_padding          5


bspc config normal_border_color "#7ccdfd"
bspc config active_border_color "#7ccdfd"
bspc config focused_border_color "#f5748c"
bspc config presel-feedback_colour "#fc9d63"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#AutoStart Application
nitrogen --restore /home/ht/.config/wall-paper/*
polybar &
#picom &
